name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      # Actualizado de v3 a v4
      uses: actions/checkout@v4

    - name: Set up JDK
      # Actualizado de v3 a v4
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build APK
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Upload APK
      # ESTA ES LA CORRECCIÓN CRÍTICA: Actualizado de v3 a v4
      uses: actions/upload-artifact@v4
      with:
        name: BlackBotEk-apk
        path: app/build/outputs/apk/debug/*.apk
        
